import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Analytics } from "@vercel/analytics/react"
import { MantineProvider } from "@mantine/core";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Drill Pilot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider theme={{ colorScheme: "light" }}>
          {children}
          <Toaster
            position="top-center"
            toastOptions={{
              className: "",
              style: {
                border: "2px solid #242423",
                color: "black",
              },
              success: {
                iconTheme: {
                  primary: "#eab308",
                  secondary: "black",
                },
              },
              error: {
                iconTheme: {
                  primary: "red",
                  secondary: "black",
                },
              },
            }}
            containerStyle={{
              top: 20,
              left: 20,
              bottom: 20,
              right: 20,
            }}
          />
          <Analytics />
        </MantineProvider>
      </body>
    </html>
  );
}
